version: "3.7"

services:
  server:
    build:
      context: ./server
      target: production-build-stage
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server/:/app
      - /app/node_modules
      - ./logs:/app/dist/logs
    restart: always
  client:
    build:
      context: ./client
      target: caddy-stage
      dockerfile: ./Dockerfile
    ports:
      - "443:3000"
    volumes:
      - ./client/:/app
      - /app/node_modules
    restart: always
    depends_on:
      - server
