version: "3.7"

services:
  server:
    build:
      context: ./server
      target: production-build-stage
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - /app/node_modules
    restart: "unless-stopped"
  client:
    build:
      context: ./client
      target: caddy-stage
      dockerfile: ./Dockerfile
    ports:
      - "80:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    restart: "unless-stopped"
    depends_on:
      - server
