# baseURL
@baseURL = http://localhost:8000/api/auth

###
# User Login
POST {{ baseURL }}/login 
Content-Type: application/json

{
    "username": "yuri01.paoloni",
	"password": "$9zdE!qS"
}

###
# Logout
GET {{ baseURL }}/logout 

###
# Validate access token
GET {{ baseURL }}/validate 

###
# Change user type
GET {{baseURL}}/userType/0

###
#
GET {{baseURL}}/changeRole/2