tags:
  - name: auth
    description: auth API
  - name: jobs
    description: jobs API
  - name: profile
    description: profile API
  - name: softSkill
    description: softSkill API

paths:
  /auth/login:
    post:
      tags:
        - auth
      summary: Authenticate a user and set auth cookie
      parameters:
        - name: body
          in: body
          description: login data
          required: true
          schema:
            $ref: '#/definitions/loginDto'
      responses:
        200:
          description: Successful login
          headers:
            Set-Cookie:
              type: string
              description: Auth cookie
          schema:
            type: object
            properties:
              tipoUtenteId:
                type: integer
              message:
                type: string
        401:
          description: 'Wrong auth token'
        404:
          description: 'Missing auth token'
        500:
          description: 'Server Error'

  /auth/logout:
    get:
      security:
        - cookieAuth: []
      tags:
        - auth
      summary: Perform logout and unset auth cookie
      responses:
        200:
          description: Successful logout
          headers:
            Set-Cookie:
              type: string
              description: Emptied cookie
          schema:
            type: object
            properties:
              message:
                type: string
        401:
          description: 'Wrong auth token'
        404:
          description: 'Missing auth token'
        500:
          description: 'Server Error'

  /auth/validate:
    get:
      tags:
        - auth
      summary: Validate an auth cookie
      responses:
        200:
          description: Cookie validated
          schema:
            type: object
            properties:
              tipoUtenteId:
                type: integer
              username:
                type: string
              message:
                type: string
        401:
          description: 'Wrong auth token'
        404:
          description: 'Missing auth token'
        500:
          description: 'Server Error'

  /auth/userType/{userType}:
    get:
      tags:
        - auth
      summary: Change usertype
      parameters:
        - name: userType
          in: path
          description: User type, can be 1, 2, or 3
          required: true
          type: integer
      responses:
        200:
          description: Changed user type
          headers:
            Set-Cookie:
              type: string
              description: Auth cookie
          schema:
            type: object
            properties:
              tipoUtenteId:
                type: integer
              message:
                type: string
        401:
          description: 'Wrong auth token'
        404:
          description: 'Missing auth token'
        500:
          description: 'Server Error'

definitions:
  loginDto:
    type: object
    required:
      - username
      - password
    properties:
      username:
        type: string
        description: unicam username
      password:
        type: string
        description: unicam password

securityDefinitions:
  cookieAuth:
    type: apiKey
    in: cookie
    name: Authorization

schemes:
  - https
  - http
