tags:
  - name: auth
    description: auth API
  - name: jobs
    description: jobs API
  - name: profile
    description: profile API
  - name: softSkill
    description: softSkill API

paths:
  /auth/login:
    post:
      tags:
        - auth
      summary: Authenticate a user and set auth cookie
      parameters:
        - name: body
          in: body
          description: login data
          required: true
          schema:
            $ref: '#/definitions/loginDto'
      responses:
        200:
          description: Successful login
          headers:
            Set-Cookie:
              type: string
              description: Auth cookie
          schema:
            type: object
            properties:
              tipoUtenteId:
                type: integer
              message:
                type: string
        401:
          description: 'Wrong auth token'
        404:
          description: 'Missing auth token'
        500:
          description: 'Server Error'

  /auth/logout:
    get:
      security:
        - cookieAuth: []
      tags:
        - auth
      summary: Perform logout and unset auth cookie
      responses:
        200:
          description: Successful logout
          headers:
            Set-Cookie:
              type: string
              description: Emptied cookie
          schema:
            type: object
            properties:
              message:
                type: string
        401:
          description: 'Wrong auth token'
        404:
          description: 'Missing auth token'
        500:
          description: 'Server Error'

  /auth/validate:
    get:
      security:
        - cookieAuth: []
      tags:
        - auth
      summary: Validate an auth cookie
      responses:
        200:
          description: Cookie validated
          schema:
            type: object
            properties:
              tipoUtenteId:
                type: integer
              username:
                type: string
              message:
                type: string
        401:
          description: 'Wrong auth token'
        404:
          description: 'Missing auth token'
        500:
          description: 'Server Error'

  /auth/userType/{userType}:
    get:
      security:
        - cookieAuth: []
      tags:
        - auth
      summary: Change usertype
      parameters:
        - name: userType
          in: path
          description: User type, can be 1, 2, or 3
          required: true
          type: integer
      responses:
        200:
          description: Changed user type
          headers:
            Set-Cookie:
              type: string
              description: Auth cookie
          schema:
            type: object
            properties:
              tipoUtenteId:
                type: integer
              message:
                type: string
        401:
          description: 'Wrong auth token'
        404:
          description: 'Missing auth token'
        500:
          description: 'Server Error'

  /profile:
    get:
      security: 
        - cookieAuth: []
      tags:
        - profile
      summary: Get user profile data
      responses:
        200:
          description: Profile data
          schema:
            $ref: '#/definitions/user'
        401:
          description: 'Wrong auth token'
        404:
          description: 'Missing auth token'
        500:
          description: 'Server Error'

    post:
      security: 
        - cookieAuth: []
      tags:
        - profile
      summary: Update user profile data
      parameters:
        - name: body
          in: body
          description: profile data
          required: true
          schema:
            $ref: '#/definitions/updateProfileDto'



definitions:
  loginDto:
    type: object
    required:
      - username
      - password
    properties:
      username:
        type: string
        description: unicam username
      password:
        type: string
        description: unicam password

  user:
    type: object
    required:
      - cf
      - nome
      - cognome
      - username
      - email
      - annoPrimaOccupazione
      - annoIngressoUnicam
      - preparazione
    properties:
      cf: 
        type: string
        description: fiscal code
      nome: 
        type: string
        description: name
      cognome: 
        type: string
        description: surname
      username: 
        type: string
        description: username
      email: 
        type: string
        description: email address
      annoPrimaOccupazione: 
        type: integer
        description: year of first work occupation
      annoIngressoUnicam: 
        type: integer
        description: Unicam entry year
      preparazione: 
        type: string
        description: degree

  updateProfileDto:
    type: object
    required:
      - firstOccupationYear
      - preparation
      - languages
    properties:
      firstOccupationYear:
        type: integer
        description: year of first work occupation
      preparation:
        type: string
        description: degree
      languages:
        type: array
        description: array of languages
        items:
          type: object
          required:
            - id
            - lingua
            - livello
          properties:
            id:
              type: integer
              description: id
            lingua:
              type: string
              description: language name
            livello:
              type: string
              description: level (e.g. A1, A2, B1, B2, ...)


securityDefinitions:
  cookieAuth:
    type: apiKey
    in: cookie
    name: Authorization

schemes:
  - https
  - http
